[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "optiland"
version = "0.0.1"
authors = [
  { name="Kramer Harrison", email="kdanielharrison@gmail.com" },
]
description = ""
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "scipy",
    "pyyaml",
    "matplotlib",
    "vtk"
]

[project.urls]
"Homepage" = "www.google.com"

[tool.setuptools]
packages = ["optiland"]