[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "optiland"
version = "1.0.0"
authors = [
  { name="Kramer Harrison", email="kdanielharrison@gmail.com" },
]
description = ""
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "scipy",
    "pyyaml",
    "matplotlib",
    "vtk",
    "tabulate"
]

[project.urls]
"Homepage" = "https://github.com/HarrisonKramer/optiland"

[tool.setuptools]
packages = ["optiland"]