[tool.poetry]
name = "optiland"
version = "0.2.4"
description = "Comprehensive optical design, optimization, and analysis in Python."
authors = ["Kramer Harrison <kdanielharrison@gmail.com>"]
readme = "README.md"
license = "MIT"
homepage = "https://github.com/HarrisonKramer/optiland"
python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]

[tool.poetry.dependencies]
numpy = "*"
scipy = "*"
pandas = "*"
pyyaml = "*"
matplotlib = "*"
vtk = "*"
tabulate = "*"
numba = "*"
requests = "*"
seaborn = "*"

[tool.poetry.include]
files = [
    "optiland/database/*.csv",
    "optiland/database/*.npy",
    "optiland/database/**/*.yml"
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
